// Generated by CoffeeScript 1.4.0
(function() {
  var copyObject, crypto, hash, keys, map, padNumToString, syncLoop, toNum;

  crypto = require("crypto");

  hash = function(obj) {
    var oHash;
    oHash = void 0;
    oHash = crypto.createHash("sha1");
    oHash.update(JSON.stringify(obj));
    return oHash.digest("hex");
  };

  padNumToString = function(num, padString) {
    var p;
    p = padString;
    return p.slice(0, p.length - num.toString().length) + num.toString();
  };

  keys = function(obj) {
    var i;
    keys = [];
    for (i in obj) {
      if (obj.hasOwnProperty(i)) {
        keys.push(i);
      }
    }
    return keys;
  };

  toNum = function(obj) {
    return parseInt(obj, 10);
  };

  copyObject = function(obj) {
    return JSON.parse(JSON.stringify(obj));
  };

  map = function(f, obj) {
    var i, o;
    o = copyObject(obj);
    for (i in o) {
      o[i] = f(o[i]);
    }
    return o;
  };

  syncLoop = function(options, i, cb) {
    var compute, condition, item, list, params, res,
      _this = this;
    list = options.list;
    condition = options.condition;
    compute = options.compute;
    params = options.params;
    res = options.res;
    if (i < list.length) {
      item = list[i];
      if (condition(item, params)) {
        return compute(item, params, function(r) {
          res.push(r);
          return syncLoop(options, i + 1, cb);
        });
      } else {
        return syncLoop(options, i + 1, cb);
      }
    } else {
      return cb(null, res);
    }
  };

  module.exports = {
    hash: hash,
    padNumToString: padNumToString,
    keys: keys,
    toNum: toNum,
    copyObject: copyObject,
    map: map
  };

}).call(this);
